# Generated by Django 3.2.13 on 2023-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_upload_equalized_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Equalized_image',
        ),
    ]
