# Generated by Django 3.2.16 on 2023-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_upload_equalized_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Equalized_image',
        ),
        migrations.AddField(
            model_name='upload',
            name='InfectedRegion',
            field=models.ImageField(default=1, upload_to='spot_on_org_images'),
            preserve_default=False,
        ),
    ]
