# Generated by Django 4.1.7 on 2023-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_rename_treatment_treatment_caused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='caused',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='chemical_control',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='disease',
            field=models.CharField(choices=[('Bacterial Blight', 'Bacterial Blight'), ('Leaf Rust', 'Leaf Rust'), ('Leaf Spot', 'Leaf Spot'), ('Mite Insect', 'Mite Insect'), ('Red Rot', 'Red Rot'), ('Red Rust', 'Red Rust'), ('White Fly', 'White Fly'), ('Yellow Leaf Virus', 'Yellow Leaf Virus')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='organic_control',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='preventive_measures',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='symptoms',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
