# Generated by Django 4.1.7 on 2023-04-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_alter_treatment_caused_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
