# Generated by Django 4.1.7 on 2023-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img/'),
        ),
    ]
